### ISSUE TITLE
Browser builds repo

### ISSUE THREAD

**Issue by axic** [ethereumjs/ideas#7]
As a follow up solution to https://github.com/ethereumjs/ideas/issues/5.

I propose to create a repository called `ethereumjs-browser-builds` or `browser-builds`, which would have stable browserified builds of:
- `ethereumjs-tx`
- `ethereumjs-vm`
- an all-in-one build containing both `ethereumjs-tx` and `ethereumjs-vm`
- perhaps other combination as need arises?

These builds could also have the es6 shim included.

This way the exports in #5 could be removed (and they wont pollute the namespace) and there would be a simple maintained repo for those not wanting to use dependency management themselves.

Note that currently neither in tx or vm the builds are run with every release, so they are outdated.

**Comment by axic** [comment]
cc @wanderer @kumavis

**Comment by wanderer** [comment]
Sounds good, how would do we automate this?

**Comment by flyswatter** [comment]
To automate will need a server that is always running that can receive github web hooks on those repos, performs the build, and pushes the changes to github, npm, bower, whatever.

**Comment by wanderer** [comment]
ill help pay for servers if someone wants to set it up!

**Comment by axic** [comment]
At the moment I wouldn't, we don't have that many releases, but as @flyswatter says it could be done with hooks and servers.

I'll push my sample build code to `browser-builds` to get started?

**Comment by wanderer** [comment]
@axic sounds good

**Comment by axic** [comment]
Here: https://github.com/ethereumjs/browser-builds. Feel free to change anything or remove any libs.

One important change from the current -vm and -tx builds is the naming, see #5 what those export.

In the new version every single dist file exports a global called EthJS which is then populated with the included libraries. For VM:

```js
module.exports = {
  Account: require('ethereumjs-account'),
  Buffer: require('buffer'),
  BN: require('ethereumjs-util').BN,
  RLP: require('ethereumjs-util').rlp,
  Trie: require('merkle-patricia-tree'),
  Util: require('ethereumjs-util'),
  VM: require('ethereumjs-vm')
}
```

**Comment by axic** [comment]
I've just realised that goes back to the naming used by 'ethereumjs-lib'.

**Comment by flyswatter** [comment]
Sounds right to me!

- Dan

**Comment by kumavis** [comment]
we could just provide a link to the bundle produced by browserifyCDN (actually theres 2 such services)

* https://wzrd.in/ (seems to be up) https://wzrd.in/standalone/ethereumjs-vm@latest
* https://www.brcdn.org/ (down as of this writing) https://www.brcdn.org/?module=ethereumjs-vm&version=1.2.1

**Comment by axic** [comment]
@kumavis I like it! Does it support similar level of fine tuning done in `browser-builds`? e.g. to have different set of included packages.

**Comment by axic** [comment]
Since we have https://github.com/ethereumjs/browser-builds I think we can consider this closed.
